// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ugydhonclcdhgfcuevcd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVneWRob25jbGNkaGdmY3VldmNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxNDM1NjIsImV4cCI6MjA1ODcxOTU2Mn0.JiJFrHp4UC1WNDsy-0Qe_hirCiAHNR9HsGRmGtu1PSM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);